### ISSUE TITLE
多人并行开发时，是否支持excel文件合并

### ISSUE THREAD

**Issue by wangzhanxian** [focus-creative-games/luban#100]

**Comment by pirunxi** [comment]
table的input设置为多个文件就可以了。参考数据源相关文档

**Comment by yuanxiao1234** [comment]
数据源相关文档的链接可以粘贴出来嘛，没有找到。我也是遇到问题了，团队开发中如果大家都改动了一个excel，合并的时候就会有冲突，现在解决冲突是给合并分支的改动从excel中拷贝一份出来，粘贴到被合并的分支上excel中。这样合并内容就感觉很繁琐。

**Comment by pirunxi** [comment]
excel文件在团队协作时的冲突问题不是luban自身能解决的，已经完全超出了luban的工作范畴。luban能做到的是支持csv、json、xml等等方便团队协作的数据源。 你可以考虑使用在线表格，然后在luban中新增数据源直接读取在线表格数据，或者将在线表格数据下载到本地后再生成。
