### ISSUE TITLE
 关于模板里面的这个方法是用来做什么的啊，删除了会不会有影响public  void ResolveRef(Tables tables)

### ISSUE THREAD

**Issue by singleTree** [focus-creative-games/luban#101]

**Comment by pirunxi** [comment]
对于类似`<var name="id" type="int#ref=xx"/> 带有ref的字段，为额外为它生成一个字段，指向了对应表中的那个记录的引用，方便开发者使用。 这个引用的赋值在 ResolveRef函数中完成。因此你如果用不到这种机制，是可以删除的
