### ISSUE TITLE
嵌套集合list<list>生成的typescript有编译问题，java没问题

### ISSUE THREAD

**Issue by 3ho** [focus-creative-games/luban#104]
![image](https://github.com/focus-creative-games/luban/assets/31562720/d61bbbe5-b172-42f2-a260-8a1a6297d5dc)
如图(list#sep=;),((list#sep=|),int)，数据2|30|1000;3|30 生成的java没问题，生成的typescript有编译问题
![image](https://github.com/focus-creative-games/luban/assets/31562720/39ac55bf-7995-4920-9e43-40898e7b8a36)
感谢大佬分享

**Comment by pirunxi** [comment]
v2.1.11版本修复了这个问题。你从release下载最新或者自己重新构建即可。
