### ISSUE TITLE
值类型生成的代码错误

### ISSUE THREAD

**Issue by Keeyuu** [focus-creative-games/luban#106]
定义如下 
    \<bean name="PeopleAge" valueType="1" \>

生成的代码 
namespace cfg
{
public partial struct PeopleAge
...
  public PeopleAge GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;

值类型没有null

**Comment by pirunxi** [comment]
确实是有一个bug，我们会修复它。不过table的行结构不推荐为struct类型，这个会显著增加开销
