### ISSUE TITLE
对于Unity中导出JsonC#类，如果需要code_target支持newtonsoft-json或者JsonUtility对应的数据模型，请问有扩展的可能吗？

### ISSUE THREAD

**Issue by jojo-WJ** [focus-creative-games/luban#107]
对于Unity中导出JsonC#类，如果需要code_target支持newtonsoft-json或者JsonUtility对应的数据模型，请问有扩展的可能吗？

**Comment by jojo-WJ** [comment]
目前的 code_target 导出的SimpleJson、EditorJson、donetJson ，期待对于Unity本身的JsonUtilty和newtonsoft-json进行类型支持！

**Comment by pirunxi** [comment]
能，仿照现有的实现做一个就可以了。如果你已经支持了，欢迎pr给我们。  由于simplejson库本身很小，纯粹是承担加载json的任务。建议是没必要折腾这些。反正都是自动加载的。
