### ISSUE TITLE
空列表读取错误

### ISSUE THREAD

**Issue by DustinMaple** [focus-creative-games/luban#114]
按照文档中的介绍，如果bean中的List字段想配置为空列表，需要使用`}`占位，我这样做了之后，还是会有报错。我的定义和数据如下：
<img width="418" alt="image" src="https://github.com/focus-creative-games/luban/assets/14121924/b8efcbca-4d82-4ea0-a70c-070dffd19965">

<img width="239" alt="image" src="https://github.com/focus-creative-games/luban/assets/14121924/c680697a-2dd2-4e43-bfa5-74b9b9c6c85a">

报错是：
缺少数据
MyBean.testBean => {TestBean}.b

我debug了一下，发现是读取TestBean的时候，读取到字段l时，ExcelStreamDataCreator.ReadList方法中，在循环读取元素之前，调用了一次TrySep，这次调用中，将`}`读取出去了，然后把`2`作为列表的元素了，所以在读取字段b的时候，就没有数据了。

**Comment by pirunxi** [comment]
你的写法是错的，sep必须写到type上，例如 type="(list#sep=,),int"。你直接去新手群问吧。
