### ISSUE TITLE
没有设置导出的组也会检查ref, 导致报错：ref 引用的表 xxx 没有导出

### ISSUE THREAD

**Issue by EP-Toushirou** [focus-creative-games/luban#116]
UnitConfig和AIConfig都在c组，但现在仅想导出Release组

![image](https://github.com/focus-creative-games/luban/assets/45257277/199f737a-79f5-432e-b6bf-6e5748a26dd1)
![image](https://github.com/focus-creative-games/luban/assets/45257277/81636143-389d-46b4-87e8-06cf8e2d1395)
![image](https://github.com/focus-creative-games/luban/assets/45257277/4bb32e67-2f78-4d68-a6d9-1de6a06d620f)
![image](https://github.com/focus-creative-games/luban/assets/45257277/45ea5754-9233-4ba0-b0c1-3efa4707784f)
![image](https://github.com/focus-creative-games/luban/assets/45257277/f8d64aa4-59fc-4c2d-afd3-2f0c0bfb9afc)

**Comment by pirunxi** [comment]
我们会尽快解决这个问题

**Comment by EP-Toushirou** [comment]
收到 谢谢

**Comment by pirunxi** [comment]
已经修复此问题. 下载最新的v2.1.13版本即可。
