### ISSUE TITLE
是否能考虑添加typescript_bin的支持

### ISSUE THREAD

**Issue by Alistairot** [focus-creative-games/luban#117]
rt 原来的classic版本是有的，现在新版是否有计划添加typescript_bin呢

**Comment by Alistairot** [comment]
官网文档那里二进制的支持是打钩了的

![image](https://github.com/focus-creative-games/luban/assets/133481301/69facbf1-df1f-4f88-96cd-7984fcf82e69)

**Comment by pirunxi** [comment]
旧版本是支持的，但新版本没有移植。因为感觉这个BinaryReader十分低效。 你暂时可以参照旧版本实现这个typescript-bin的支持。我们后面如果重新支持的话，会再次回复你的
