### ISSUE TITLE
type=int?! 校验器无效果

### ISSUE THREAD

**Issue by FistChina** [focus-creative-games/luban#118]
type=int?!我测试了下没效果，不填数据和填null都可以通过
![image](https://github.com/focus-creative-games/luban/assets/29481291/608fa0fa-90d7-41cb-8f9c-6bfbb180f082)
![image](https://github.com/focus-creative-games/luban/assets/29481291/ab107f8b-5f07-4b4b-a09b-42f3679f6c85)

**Comment by pirunxi** [comment]
可空数据不会检查默认值。因为既然都不是默认值，为何要为可空类型
