### ISSUE TITLE
Excel导出lua数据 数值做key问题

### ISSUE THREAD

**Issue by qq353571619** [focus-creative-games/luban#12]
![image](https://user-images.githubusercontent.com/17849277/173298533-49c73725-a29e-4640-915b-83cd50e6183c.png)
![image](https://user-images.githubusercontent.com/17849277/173298619-c76f98e4-ca82-485a-85d9-677bef3e4b0d.png)

**Comment by pirunxi** [comment]
luban 不接受数字为字段名，因为正常情况下，字段名在生成代码时会用到。只不过luban没检查字段名合法性，导致你可以顺利生成。如果有其他问题，到QQ群直接找我们，反馈比较及时。
