### ISSUE TITLE
能否为生成类型添加克隆函数

### ISSUE THREAD

**Issue by 164105419** [focus-creative-games/luban#120]
我想将配置类直接作为运行时的类使用. 比如说我配置一个行为树节点,我希望这个节点有自己的运行时数据.但是如果配置两个相同节点就会导致运行时数据共用.

**Comment by pirunxi** [comment]
首先 不推荐。因为配置是不可变数据，运行时类型请单独创建实例，包含指向配置的引用。

其次你自己改模板实现这个需求
