### ISSUE TITLE
输出的json文件，可以不要格式化吗？

### ISSUE THREAD

**Issue by AnYuanLzh** [focus-creative-games/luban#123]
输出的json文件，可以不要格式化吗？格式化的json文件大了很多，可以的话要如何设置

**Comment by pirunxi** [comment]
有一个pretty print参数，我们明天看一下

**Comment by pirunxi** [comment]
-x json.compact=1 就不格式化了，紧凑输出

**Comment by AnYuanLzh** [comment]
![image](https://github.com/focus-creative-games/luban/assets/3367169/2f1d0ecd-97a2-4af5-a31c-4122de44c884)
像不起作用，结果都一样

**Comment by AnYuanLzh** [comment]
再看了一下源码，发现写成：
    -x tableExporter.json.compact=1
或直接简写成：
    -x compact=1
就可以紧凑输出了

**Comment by pirunxi** [comment]
确实如此。不过这个参数名不是很妥当，我们在v2.3.1版本调整了此参数，改成了 -x json.compact=1 或 -x compact=1
