### ISSUE TITLE
lua 多主键表（独立索引）生成代码问题

### ISSUE THREAD

**Issue by zengdonghai** [focus-creative-games/luban#132]
![image](https://github.com/focus-creative-games/luban/assets/16550467/fe6e6d9e-0092-41b5-99e3-9c786fc740f5)
![image](https://github.com/focus-creative-games/luban/assets/16550467/be2fd5b6-a659-4ae7-942a-7d98523cf3bb)
我想配置一个配置表的Id,Domain两个为独立的键，生成对应独立的map映射表，在lua的表示中，只生成上图这种list的格式，这种多主键表（独立索引）配置方式，在lua貌似不生效

**Comment by zengdonghai** [comment]
![image](https://github.com/focus-creative-games/luban/assets/16550467/40286aa1-9998-46d6-aa00-6df61cb3a1ad)
图f发错了，对应生成了这种list格式，

**Comment by zengdonghai** [comment]
![image](https://github.com/focus-creative-games/luban/assets/16550467/04f1140e-3186-488b-9587-01e313d3b7f9)
理想是应该这种map的格式。当然这里还可以优化，value的引用

**Comment by pirunxi** [comment]
这是已知问题，很多语言并没有内置的多key索引的支持，因此由开发者自己选择合适的实现。写一个make_index2函数就能较好达到效果。

**Comment by zengdonghai** [comment]
那是需要自己修改代码生成的源码咯？如果是这样那我自己定制一个生成器吧。

**Comment by pirunxi** [comment]
我觉得没必要改源码。 你实现一个make_index函数将列表转换为你想要的索引方式即可 ，代码类似这样
```lua
function make_index(t, key1, key2)
  
   local nt = {}
   for _, v in ipairs(t) do 
     nt[v[key1]] = v
     nt[v[key2]] = v
  end
    return nt
end
```

**Comment by zengdonghai** [comment]
了解，谢谢！
