### ISSUE TITLE
2.6.2 go generate failed error

### ISSUE THREAD

**Issue by chasinghope** [focus-creative-games/luban#136]
![Snipaste_2024-05-06_12-12-05](https://github.com/focus-creative-games/luban/assets/42870306/9ffe6227-20f0-4583-86d1-4013c3680789)

**Comment by chasinghope** [comment]
![Snipaste_2024-05-06_12-14-34](https://github.com/focus-creative-games/luban/assets/42870306/e6488001-7dad-4aed-8c4c-1935ab6a7f5c)

**Comment by IndiaGameMaker** [comment]
这个问题怎么解决啊？

**Comment by HanNayun** [comment]
Hi! I encounter same error, how you fix it
