### ISSUE TITLE
嵌套容器类型的 ref 校验失效

### ISSUE THREAD

**Issue by alex4814** [focus-creative-games/luban#138]
对于一个类型为 `list,list,(list#sep=,),(int#ref=levels.TbCellElement)` 的字段，该 *ref* 校验没有生效。

填表如下
![3fbbd2774624ab419cb782cc60a57505](https://github.com/focus-creative-games/luban/assets/963917/84b80f07-9455-4b71-bd1e-210b4dcd990b)

生成数据如下
![2210c5ec5d33a04494e02b27689d02c8](https://github.com/focus-creative-games/luban/assets/963917/5b5bd6ed-f67a-42f0-92f2-28b235e0f153)

经过调试发现，目前代码在 List 类型中，仅支持 bean 类型的 validator，但看代码逻辑应当是可以直接支持递归。
![image](https://github.com/focus-creative-games/luban/assets/963917/bae9960e-a395-4751-b73f-d6cedcba4297)

**Comment by pirunxi** [comment]
ok。等你更新代码后我们合并这个改动
