### ISSUE TITLE
go-json无法导出嵌套容器

### ISSUE THREAD

**Issue by fghj0810** [focus-creative-games/luban#140]
![图片](https://github.com/focus-creative-games/luban/assets/13959080/20c4dcc5-06fd-47a1-9f19-3c145b5c3374)
![图片](https://github.com/focus-creative-games/luban/assets/13959080/7ee5d63a-9b9e-4b8e-9e3b-aee0e6aa2ccc)

**Comment by pirunxi** [comment]
go-json代码确实不支持嵌套容器，这个我们后面会改一下
