### ISSUE TITLE
java怎么生成到指定包名下

### ISSUE THREAD

**Issue by 3ho** [focus-creative-games/luban#153]
![image](https://github.com/focus-creative-games/luban/assets/31562720/d1dd4591-ab2a-40f7-9f2e-0ecc77479c81)
强哥 上面那个package通过配置luban.conf解决了。
但是下面那个import luban.*; 怎么改成import com.juyou.p88.common.luban.*;

**Comment by 3ho** [comment]
因为生成的cfg代码继承了luban.AbstractBean。我想把luban文件夹放到com.juyou.p88.common下

**Comment by absences** [comment]
修改Templates /java*  /table.sbn 文件，代码是以此为模板生成

**Comment by pirunxi** [comment]
如 absences所说
