### ISSUE TITLE
在 M1 芯片 Mac 上执行 MiniTemplate 中的 gen.sh 会报错

### ISSUE THREAD

**Issue by shroudpatric** [focus-creative-games/luban#16]
在 M1 芯片 Mac 上执行 MiniTemplate 中的 gen.sh 会报错，报错信息如下：

`
./gen.sh:4: exec format error: ../Tools/Luban.ClientServer/Luban.ClientServer.dll
`

请问是什么问题

**Comment by LiuOcean** [comment]
#!/bin/zsh 换成 #!/bin/bash 试试

**Comment by shroudpatric** [comment]
> #!/bin/zsh 换成 #!/bin/bash 试试

得到下面这个报错
./gen.sh: line 4: ../Tools/Luban.ClientServer/Luban.ClientServer.dll: cannot execute binary file

**Comment by LiuOcean** [comment]
来 QQ 群把。692890842，帮你瞅瞅。

**Comment by shroudpatric** [comment]
经过大佬指点，将 gen.sh 文件中对应代码部分做出修改即可。

`
//${GEN_CLIENT} -j cfg --\  
dotnet ${GEN_CLIENT} -j cfg --\
`
