### ISSUE TITLE
有没有办法让Bean类型用一个特殊占位符作为默认值

### ISSUE THREAD

**Issue by FlowSand** [focus-creative-games/luban#167]
实际开发工作中，策划想用某些特殊符号作为bean类型默认值，比如 / ，期望此时代表bean类型各个字段成员保持默认值，空单元格则会认作未处理的内容，不知道是否支持此类配置方式
现在使用上，发现可以将bean类型设置为可空类型，并将单元格填写为null，但是写代码会比较麻烦而且和留空得到的意义不同

**Comment by pirunxi** [comment]
这种你们个人偏好的习惯不能放到公共实现中。另外luban中bean自身可能嵌套bean，如何bean的第一个字段是bean,你用/表达整个bean是默认值，还是第一个字段是默认值呢。完全无法区分。有问题去QQ群讨论吧。

**Comment by FlowSand** [comment]
好的，感谢回复~
