### ISSUE TITLE
next版本在解析纵表时，表中有空行会导致复杂结构类型数据解析报错

### ISSUE THREAD

**Issue by AILHC** [focus-creative-games/luban#169]
报错：
![cb7a89a82be2729bd7f665a3e39204a0](https://github.com/user-attachments/assets/13d37e56-aff9-4f66-bdb3-06f30dd09b95)

table定义:common.xml
复现的Excel：全局常量配置表.xlsx 
![19f3fa4cd72379d9ece217b2fc7b5be6](https://github.com/user-attachments/assets/0689f29c-87a6-40d2-89fc-359dffefce78)

我增加了个x8字段，使用类型为bean类型

bean定义:
test.TestExcelBean1
所在文件:__beans__.xlsx

我的调试
全局常量配置表.xlsx 第三行为空行
![cd2673a46b48f231fb508df0c0991991](https://github.com/user-attachments/assets/d543150a-01b8-4ce8-8092-5e5477d4bc2e)

ParseRawSheetContent时，遇到空行就跳过。
![image](https://github.com/user-attachments/assets/55a66cad-102f-4db5-a159-037e5d202cf5)

在ParseSubTitles时，mergeCells的FromRow和titleRow的数据对不上，所以解析错误，但没报错，直到解析值的时候才报错了
![d4cfbf4312a05a79cbf991ee92c0bbc1](https://github.com/user-attachments/assets/26b959b3-e29f-47c6-a252-bbd51a826014)
![d21b8beca656b24c9c6396cdef683e2e](https://github.com/user-attachments/assets/932878dc-7248-41a3-b109-d76944ae332a)

为什么classic没有这个问题，因为ParseRawSheetContent时没跳过空行
![5a65774bebdcd3d2b433a607776dae20](https://github.com/user-attachments/assets/0034ffa0-3fbf-4fa3-a926-ba45a4f82a78)

**Comment by pirunxi** [comment]
感谢，我们已经修复
