### ISSUE TITLE
Luban后面会考虑支持oneOf吗？

### ISSUE THREAD

**Issue by thrt520asd** [focus-creative-games/luban#17]
Lunban已经很好很强大了，策划的需求总是多种多样的，所以鲁班有打算支持类似protoBuff的oneof这种数据格式吗？
同一个字段里放入不同格式的复杂类型，这个很有帮助求求了~

**Comment by pirunxi** [comment]
现在已经支持多态，这个和OneOf基本等价，而且在OOP的情况下更好用。还有疑问在luban群直接问吧
