### ISSUE TITLE
在 jenkins 上使用时 path 会包含 .jenkins，会触发 IsIgnoreFile 的规则

### ISSUE THREAD

**Issue by basstal** [focus-creative-games/luban#173]
例如如下 config 就会被忽略掉。
D:\Jenkins\.jenkins\workspace\FD2\Externals\luban\luban.conf

**Comment by pirunxi** [comment]
不是只有以.开头的才会被忽略吗？你这样的也会被忽略？

**Comment by basstal** [comment]
D:\Jenkins\.jenkins\workspace  那里少了个 \ ，不过我再去确认一下为什么公司里出档机 jenkins 目录要加一个 .jenkins。可能没得必要。

**Comment by pirunxi** [comment]
之前的版本确实是有类似的bug，但需要是目录下以.开头的文件，像你这种中间有.的，如果确实能最新的v3.3.0上复制，发一个示例给我们看一下
