### ISSUE TITLE
python-json导出map容器生成代码问题

### ISSUE THREAD

**Issue by ljjlzy** [focus-creative-games/luban#174]
表定义：
![1725182838402](https://github.com/user-attachments/assets/981e17cf-2ba8-4c15-9965-0b7c76c2e1b0)

生成的json：
![1725182950447](https://github.com/user-attachments/assets/bf623271-5457-46ea-90d9-43a2fc8ccabb)

生成的代码：
![1725182990357](https://github.com/user-attachments/assets/dcab36ba-0f67-425f-89d4-7f323ff64f01)

self.effect[_k0_] = _v0_的缩进有问题

**Comment by pirunxi** [comment]
感谢反馈，我们已经解决，刚刚发布了v3.6.0
