### ISSUE TITLE
float类型存储 读取结果错误

### ISSUE THREAD

**Issue by tianma0042** [focus-creative-games/luban#177]
code target : cs-bin
data target : bin

在Unity中使用

类似这种结构 存在多个float类型的数据
![image](https://github.com/user-attachments/assets/9a1a3b69-45e7-4e09-98c7-6cdb6875541d)

获取到的数据
{ProjectLocationID:1,City:A11,State:A,ZipCode:1001,TaxRate:0.1,MaterialCostIndex:0,CarpenterCostIndex:5.884441E+11,ElectrianCostIndex:1.934887E-19,MasonCostIndex:6.947193E+22,PlumberCostIndex:9.556954E-36,}

从MaterialCostIndex开始数据就错误了， 后面的数据就全错误了。

以下是execl文件
[test.xlsx](https://github.com/user-attachments/files/17158089/test.xlsx)

**Comment by pirunxi** [comment]
不可能，你读错数据了

**Comment by tianma0042** [comment]
把 MaterialCostIndex - PlumberCostIndex 的float改成int类型 可以不改其他东西可以读出正确数据。
请问你测试了吗？ 就说我读错数据了?

**Comment by pirunxi** [comment]
不知道你哪来的底气说有bug，还说什么测试过没？l你这东西是最最常见的用法，如果这都有bug，还会这么多年来，这么多项目都没发现？？？ 你怎么不仔细对照一下读取的文件，是不是你刚刚生成的那个？？？？？？你宁愿相信机器有问题，也不愿意相信你自己有问题？？？？

![a](https://github.com/user-attachments/assets/1f9c43c4-3a54-474e-a1ba-538c82a66e84)

**Comment by tianma0042** [comment]
不好意思， 是我的问题， 是因为我使用了异步加载了.byte文件， 具体原因还在查。
