### ISSUE TITLE
生成 json 文件 行尾符配置支持

### ISSUE THREAD

**Issue by sinlov** [focus-creative-games/luban#180]
生成 文件的换行符 目前只覆盖带 代码

```
-x lineEnding=LF
```

生效实现为
[CodeWriter.cs#L19](https://github.com/focus-creative-games/luban/blob/main/src/Luban.Core/CodeTarget/CodeWriter.cs#L19)

生成其他文件

- 比如 json 也需要支持 换行

目前 json 输出设置为

[JsonDataTarget.cs](https://github.com/focus-creative-games/luban/blob/main/src/Luban.DataTarget.Builtin/Json/JsonDataTarget.cs#L30)

PS: 全平台常见的坑就 2个，一个是 文件路径，另外一个就是 行尾符

**Comment by pirunxi** [comment]
好的，我们会新增选项

**Comment by pirunxi** [comment]
我们刚刚发布了v3.9.0，支持你说的特性。你可以用 -x data.lineEnding=lf或者 -x lineEnding=lf来指定json文件的换行符
