### ISSUE TITLE
go多主键表（独立索引）无法正确生成

### ISSUE THREAD

**Issue by dager-w** [focus-creative-games/luban#181]
目前测试发现go无法正确的生成多主键独立索引,翻看了之前的issues,lua也碰到过这个问题,之后会优化吗?还是go和lua就不会支持这个功能?

**Comment by pirunxi** [comment]
这些语言没有多主键的语法或者库支持，我们勉强生成了也不能让大家满意。有需要的自己考虑改改吧。后面也不会加

**Comment by dager-w** [comment]
建议在文档中明确一下支持的语言或不支持的语言,对使用者比较友好.
