### ISSUE TITLE
请问可以对sep分隔的字符串trim吗？

### ISSUE THREAD

**Issue by gengen1988** [focus-creative-games/luban#182]
比方说策划编辑时为了让每一段区分的更明显而在分隔符后加了个空格：

![image](https://github.com/user-attachments/assets/18a312a2-fc06-4b82-bf3d-6aed1d105213)

目前的生成结果是把空格也算作 value 了： 

![image](https://github.com/user-attachments/assets/cff02415-08eb-4b1d-82af-750ebcdd7ee3)

可不可以通过配置在生成json时把字符串左右的空格去掉？

**Comment by pirunxi** [comment]
如果移除了空格，填写需要首位出现空格的字符串类型时会出问题。对于绝大多数在使用luban的项目来说，修改这个默认行为会引发严重bug。如果一定要这么做，自己改一下代码吧，也就一行代码的事
