### ISSUE TITLE
生成文件不是覆盖追加

### ISSUE THREAD

**Issue by piaolang277** [focus-creative-games/luban#24]
luban 生成文件 会先删除文件夹里的所有文件，如果有非luban 需要生成的文件在文件夹 会被删除，希望改成 覆盖追加的形式！

**Comment by pirunxi** [comment]
如果不清理，时间长了会有很多残留文件，甚至经常导致编译错误。 建议把你的代码放到其他目录，这样区分清楚，从工程角度比较合理。
