### ISSUE TITLE
請問有 微信 號, 想請教您們在excel上有對應工具? 在excel 上有與xml關聯資料驗證或方便輸入如ref設定?

### ISSUE THREAD

**Issue by linchao0815** [focus-creative-games/luban#3]
我尝试了将本地语言切到 台湾繁体，但好像没有乱码，只不过打印出来的都是简体中文。  如有可能，请注册QQ或者微信 跟我们保持联系，方便反馈和解决问题。 我们很快会考虑解决语言本地化的问题，至少提供（简体，繁体和英文）

_Originally posted by @pirunxi in https://github.com/focus-creative-games/luban/issues/2#issuecomment-888821274_

**Comment by pirunxi** [comment]
邮箱联系，我加你微信

**Comment by pirunxi** [comment]
我们有非常完整的支持。你把微信号发到taojingjian@gmail.com 我加你。明天给你解答。
