### ISSUE TITLE
技术支持真NB，技术不行，框架理解不行，回答不了就先把提出问题的人踢了，麻烦告诉我，我违反了哪条群规定

### ISSUE THREAD

**Issue by meichen8050753** [focus-creative-games/luban#41]
![image](https://user-images.githubusercontent.com/2345514/221727039-f01d0645-99fb-4065-8f20-d8e2ca6e937b.png)

**Comment by meichen8050753** [comment]
就是这样维护生态的么

**Comment by pirunxi** [comment]
聊天记录我们看到了，你发言的语气不是太好，你重新申请加群吧。
