### ISSUE TITLE
Map 支持一下 限定数据下的Bean。 现在 Map 的value是限定的Bean 就报错。

### ISSUE THREAD

**Issue by horseless123** [focus-creative-games/luban#43]
感觉这个功能挺常用的啊，难道全部要用list吗？

**Comment by pirunxi** [comment]
map已经有按key限定的模式了，再支持value像list那样展开限定的话，容易混淆使用方式。我们在考虑如何优雅解决这个问题。目前一个解决办法 是 type="list,xxx#index=key_variable_of_xxx"。这样会同时生成list和一个按xxx中的指定字段索引的map。某种程度也解决了这个问题。
