### ISSUE TITLE
请问支持从txt、json或者lua的生成文件里读取数据填充回xlsx么？

### ISSUE THREAD

**Issue by owllyi** [focus-creative-games/luban#54]
希望日常中的数据都保存在文本文件中，每次用都读回到xlsx编辑，这样xlsx就不必每次变化都上传到git了。
git上保存的都是文本的数据，xlsx就是一个编辑工具，请问这种思路可行吗，该如何操作呢？

**Comment by pirunxi** [comment]
支持，但不是特别完善，请看convert相关文档。 另外，旧版本的LubanAssistant是一个excel插件，做的正是这事。
