### ISSUE TITLE
容器嵌套容器里如果出现两个list, 数据解析会有问题

### ISSUE THREAD

**Issue by Ritchie1108** [focus-creative-games/luban#58]
这样的一个结构
![{ILA57(_W~A%RCYKYH52JBI](https://github.com/focus-creative-games/luban/assets/17867291/2a18b964-a87e-49f1-985a-d78484953cc9)
数据导出的时候, 如果 arr_1 和 arr_2 里的字段是一个字段一个格子的话, 会出现配置在 arr_2 的数据, 导出的时候解析到 arr_1 里

演示个极端的例子, arr_1 和 arr_2 稍微调整一下
![_( KOK 8W39JHULPBCP)QIM](https://github.com/focus-creative-games/luban/assets/17867291/8e2ae514-7468-4143-8422-9e7bea616666)
![6GBJS)D~CI_ S)H`$E0S)3L](https://github.com/focus-creative-games/luban/assets/17867291/34e2cc23-02fe-4741-8e85-60bd3f0c4511)

导出的数据就会有问题
![H~5)YXK$))55ZSFS(Q`}86Y](https://github.com/focus-creative-games/luban/assets/17867291/a30cfbad-3b36-4770-b244-838eb82c1090)

目前要保证数据导出没问题, 只能在 bean 里定义 sep 才能规避
![JNY 3ADGDG0 1HDD(SA}$M](https://github.com/focus-creative-games/luban/assets/17867291/2aa1c680-1fa2-460b-9b6f-d3ae49584f42)
![RV28WIZ7HQ`ZZZM`Z96KMU6](https://github.com/focus-creative-games/luban/assets/17867291/2f2e246d-1372-4c77-8d00-929b1407a15e)

**Comment by pirunxi** [comment]
这是你没理解流式和限定列格式的区别。群里讨论吧。这块没有bug。

**Comment by Ritchie1108** [comment]
懂了, 需要有读到结束标记 "}"
