### ISSUE TITLE
是否可以在业务表中定义 __tables__.xlsx 中的内容 

### ISSUE THREAD

**Issue by BinGuoGuo** [focus-creative-games/luban#59]
工具很好用，但是交由其他习惯在一个配置表中定义所有结构和内容的小伙伴来说，表示多表配置有点复杂，而且在版本管理工具环境下，__tables__.xlsx  文件容易冲突。
请问是否有方法不定义 三个 __tables,enum,bean__.xlsx 表，在业务表中就把配置内容搞定呀~

非常感谢。

**Comment by pirunxi** [comment]
虽然有可能，但这样做会严重丧失灵活性。luban的设计不仅要平衡简便性，更要适应各种复杂的项目需求。不过luban后续会有一个完全重构的版本，允许你自定制这些规则。

**Comment by BinGuoGuo** [comment]
感谢您的回复！

如果在现在版本中，我这边想去除这三个表，然后在业务表中定义原本 __tables__.xlsx 中内容，比如：

![image](https://github.com/focus-creative-games/luban/assets/30474925/a9ac129e-a128-430f-8ae6-08cfab425158)

请问在我新分支中，需要修改哪些地方才能适配代码生成和数据生成呢，或者您针对这个需求有什么建议吗。

**Comment by pirunxi** [comment]
没啥建议。乍一看不是很优雅。如果你想避免冲突，table和bean定义可以填写在xml中，方便合并。或者填到csv里也是适当的选择。
