### ISSUE TITLE
关于在 __table__.xlsx 中，input 项定义多个页签，如何只导出某一些页签的内容

### ISSUE THREAD

**Issue by BinGuoGuo** [focus-creative-games/luban#60]
作者您好：

在实际业务中，可能存在一个excel中的多个sheet中的数据结构可能一样，所以表全名和类名会一样
按照文档，我们可以在 __table__.xlsx 的 input 项以逗号分隔的形式将这些页签联合起来
此时的 group 项只能管理该项定义的所有页签

但是在某些情况下，如果我不想导出一部分页签的内容，又不能在excel中删除它，该如何定义呢？

![image](https://github.com/focus-creative-games/luban/assets/30474925/c5cc82d0-a0d0-4828-a057-96ccbc80b448)

**Comment by pirunxi** [comment]
你直接从input里删除就行了。这种使用的问题去群里问吧。
