### ISSUE TITLE
nodejs版本导出ts时，如果字段有引用类型，且原类型带问号后，引用类型会有格式报错

### ISSUE THREAD

**Issue by feelingnorth** [focus-creative-games/luban#63]
![image](https://github.com/focus-creative-games/luban/assets/99531409/eb282a4f-2059-441d-aa4d-226de99697a7)
![image](https://github.com/focus-creative-games/luban/assets/99531409/1aa40498-0779-4bde-88d2-94680d076c41)

**Comment by pirunxi** [comment]
好的。你自行改吧。我们后面会修复这个问题
