### ISSUE TITLE
在使用多行结构列表时，超过2行后protobuf 解析bytes文件失败

### ISSUE THREAD

**Issue by absences** [focus-creative-games/luban#66]
![image](https://github.com/focus-creative-games/luban/assets/49706424/6cb5d1e5-4a14-4b07-a4a5-5bcd528e1f34)

最小复现工程链接：
https://share.weiyun.com/FTX1nKoE

都是最新版本

**Comment by pirunxi** [comment]
我们复核一下，很快会解决

**Comment by pirunxi** [comment]
打开项目就有报错。请检查一下。 你还是直接群里问吧。带上材料。

**Comment by pirunxi** [comment]
这个protobuf map的bug我们刚刚在4.2.0版本修复了。确实是有问题的！
