### ISSUE TITLE
希望增加一个“是否清空 output_data_dir/output_code_dir”的选项

### ISSUE THREAD

**Issue by yzbyzz** [focus-creative-games/luban#78]
## 背景说明

- 多人开发的情况下，甲 开发 A 功能，乙 开发 B 功能。
- 有 2 个 git 仓库，分别是 程序代码 和 策划配置。
- 甲 做 A 功能，修改删除了部分字段，提交 程序代码仓库 和 策划配置仓库。
- 乙 做 B 功能，本地修改了程序代码，如果此时更新了策划配置仓库，因为本地改动较多暂未更新程序代码仓库。
- 此时，乙导出策划配置，会发现代码编译错误。
- 因为本地改动较多，不方便马上更新程序代码仓库。
- 此时，要么导出策划配置，手动将 A 功能模块相关的改动 discard，保证编译正确。
- 要么将策划配置仓库 reset 到甲的修改之前（和本地代码保持一致）。
- 无论哪种，都会对开发过程的行为有一定的限制。

## 期望

因此，希望鲁班工具可以增加“是否清空 output_dir”的选项，以此来解决上述的问题。
（这样 乙导出策划配置时，只选择导出 B 功能相关的策划配置，由于没有清空 output_dir，A 功能相关的程序代码还保持之前的状态。以此来规避该问题。）

或者，对于这种情况，有其他处理方式的话，也请指教一下。

> 目前的一个思路是将策划配置和程序代码放到同个 git 仓库，程序代码和策划配置总是对应的。
这种思路的问题：策划配置会合程序代码在同个仓库，没有那么独立，无法限制策划不小心提交不必要的改动。即便在同个仓库，程序代码和策划配置仍旧可能不匹配。当然整体来说是个可接受的方案。想看看还有没有其他思路。

**Comment by pirunxi** [comment]
已经有这样的参数了 
![image](https://github.com/focus-creative-games/luban/assets/1734651/87cb222a-e0f3-4063-a2c4-5778978d90f0) 。

详细请看 https://luban.doc.code-philosophy.com/docs/manual/commandtools。

但其实你也可以让程序提交前revert掉一些不必要的改动文件。

**Comment by yzbyzz** [comment]
感谢回复。
我使用的是 `Luban.ClientServer.dll`，但是没有看到  `-x` 这个选项，不确定是哪里搞错了。

![image](https://github.com/focus-creative-games/luban/assets/9823928/f3d9691d-5b72-4323-a989-b23bc2731655)

**Comment by pirunxi** [comment]
旧版本确实没有这类参数
