### ISSUE TITLE
关于数据文件的管理

### ISSUE THREAD

**Issue by ayamzh** [focus-creative-games/luban#8]
生成的pb和相应语言代码是要自己在代码库里管理，程序里进行本地文件读取么？可否做成lubanserver 生成数据文件后，数据文件自动同步到etcd之类的配置中心，游戏server启动后自动在本地内存缓存所有配置数据并利用watch机制订阅etcd里得数据变化，实现数据热更。这种比较适合游戏服务端的使用场景。

**Comment by pirunxi** [comment]
加载配置时，你提供一个自定义Loader就行了，从哪儿加载都是可以的。 你加QQ群 692890842 ，在群里给你更多详细回答。
