### ISSUE TITLE
忽略空白值引用不会生成代码

### ISSUE THREAD

**Issue by cybasta26** [focus-creative-games/luban#81]
新版本luban，忽略空白值的引用不会再生成代码
比如example中，ai.xml里的BehaviorTree，其中的blackboard_id因为加了ref，生成的代码里会自动生成一个BlackboardId_Ref。但是如果我把他改成可以忽略空白值的引用，生成的代码里就不会再生成BlackboardId_Ref了。
![QQ图片20231025162007](https://github.com/focus-creative-games/luban/assets/729523/341b6394-0a69-471b-8cd9-20d77f4e8ede)

调试了下模版，发现如果用field.ctype.tags['ref']拿到的引用名称是ai.TbBlackboard？,名称里是带着问号的。
看了下源码，在源码TypeTemplateExtension.cs里的GetRefTable接口是这样的，估计GetTag("ref")的返回值带着问号，作为table名去GetCfgTable就失败了，不知道是不是一个BUG

![QQ图片20231025162051](https://github.com/focus-creative-games/luban/assets/729523/0b707153-4a88-4680-92c3-22f81011ac04)

**Comment by cybasta26** [comment]
![Snipaste_2023-10-25_16-33-11](https://github.com/focus-creative-games/luban/assets/729523/e380448f-87af-4202-a1a7-6500e4fd7082)
尝试修改了一下源码编译之后，再导出确实就又能生成BlackboardId_Ref了。

**Comment by pirunxi** [comment]
这确实是一个bug。我们会在晚些时候处理它

**Comment by pirunxi** [comment]
已经修复了。v2.1.8版本
