### ISSUE TITLE
优化建议：能否在生成的代码文本头部加上指定的标记,在重新生成代码的时候,只删除有标记的代码文本文件

### ISSUE THREAD

**Issue by Arc-huangjingtong** [focus-creative-games/luban#82]
主要有以下好处
- 当我将程序集定义文件放在同文件下的时候,可以避免重复创建
- 可以减少"生成文件必须独立存放"的特性

**Comment by pirunxi** [comment]
我们要适当平衡简洁和具体需求的多样性，所以不可太可能引入这种逻辑。但我们提供了`outputSaver.{codeTarget|dataTarget}.cleanUpOutputDir` 用于不清除输出目录中的其他文件，某种程度也达到你这种需求。
