### ISSUE TITLE
生成的golang代码，多主键索引有问题

### ISSUE THREAD

**Issue by czdj** [focus-creative-games/luban#83]
![image](https://github.com/focus-creative-games/luban/assets/10113389/3363aca1-6955-4917-8207-2e29adfade5d)

**Comment by pirunxi** [comment]
这是预期中的。很多语言没有内置的多重索引的支持，如果我们自己引入一些支持，很难让大家都满意。所以除了c#之类的少数几种语言外，多重索引只会在导出数据时检查，生成的代码只包含列表，而未对其进行索引。
