### ISSUE TITLE
[feature request] 通过某个列的值限定另一多态列的子类型

### ISSUE THREAD

**Issue by tanghuipang** [focus-creative-games/luban#84]
例如某一物品表，有字段 id, itemType, itemValue, ... ，itemValue是多态字段，可以根据itemType确定itemValue的具体类型，按现在的做法需要策划在表中新加一列标明类型，或者在itemValue前面附上类型 如 ListOfInt:1,2,3 这两种写法都需要策划了解并填入正确的多态类型名。
希望在表格schema中可以配置一个映射表，设置不同的ItemType对应的ItemValue类型，而不需要策划在每行数据中填入。

**Comment by pirunxi** [comment]
从实现角度来说，不可能。因为不同多太类型的字段可能是相同的。另外，luban支持任意复杂的数据结构，在配合sep及流式格式的情况下，有可能会有歧义，解析器不可能能智能分析出这些情况。 

目前已经可以使用用别名，已经算是比较友好了。 策划再不方便，从他的角度，不填个类型，类型多了后，后面维护的人怎么会知道是哪个？
