### ISSUE TITLE
在类型为(map#sep=,),string,int情况下CollectionToString接口生成的字符串没有左大括号{

### ISSUE THREAD

**Issue by tzwyf** [focus-creative-games/luban#88]
表现为自动生成的继承自Luban.BeanBase的类的ToString接口返回的字符串不符合json格式
具体接口：CollectionToString<TK, TV>(IDictionary<TK, TV> dic)

**Comment by pirunxi** [comment]
为了简洁起见，ToString返回的只是可阅读的字符串，并不是json字符串，如果需要返回json字符串请修改实现或者使用其他Json库来序列化。
