### ISSUE TITLE
请问是否支持按字段过滤表格导出？

### ISSUE THREAD

**Issue by c3076802** [focus-creative-games/luban#9]
你好，请问一下luban是否支持设置单个字段过滤导出？
1. 比如说一个怪物表我们配置了资源路径，这个字段后端不需要，是否能导出的时候过滤掉
2. 比如说怪物表我们有一个后端的AI配置项，前端不需要，是否能导出的时候过滤掉

感谢

**Comment by LiuOcean** [comment]
int&group=c 仅客户端导出
int&group=s 仅服务端导出

692890842 QQ 群问问题更快一些噢。

**Comment by c3076802** [comment]
感谢
